DOT_DIR="$HOME/dotfiles"
PYDIST_DIR="$HOME/miniforge3"

alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias sl='sudo ls -alF'
alias v='vim -u "$DOT_DIR/vimrc"'
alias sv='sudo vim -u "$DOT_DIR/vimrc"'
alias g='git -c "include.path=$DOT_DIR/gitconfig"'
alias t='tmux new-session -s'
alias tl='tmux list-sessions'
alias ta='tmux attach-session -t'
alias p='python3'
alias h='eval "$($PYDIST_DIR/bin/conda shell.bash hook)"'
alias e='conda create -n'
alias a='conda activate'
alias d='conda deactivate'
alias i='conda install'
alias x='conda remove --all -n'
alias n='nvtop -p'
alias c='clear'
