#!/bin/bash

DIR="${BASH_SOURCE%/*}"
if [ ! -d "$DIR" ]; then
    DIR="$PWD";
fi

if [ -n "$DT_CONDA_ENV" ]; then
    PATH="$HOME/anaconda3/envs/$DT_CONDA_ENV/bin:$PATH"
fi

if [ "$1" = 'run' ]; then # execute command

    date
    echo "==="
    $DT_RUN_CMD$DT_FILE
    echo "==="
    date

elif [ "$1" = 'pyl' ]; then # pylint

    pylint --output-format=text --msg-template="{path}:{line}: [{symbol}] {msg}" --reports=no "$DT_FILE"

elif [ "$1" = 'cal' ]; then # calculate

    echo "$2" | bc

elif [ "$1" = 'git' ]; then # git shell

    bash --rcfile "$DIR/git-env/.bashrc"
    # zsh variant:
    # ZDOTDIR="$DIR/git-env" zsh

elif [ "$1" = 'sql' ]; then # query database

    cmd="mysql --login-path=$DT_DB_PATH -vv"
    query="${DT_SQL_QUERY//\"/\\\"}";
    case $query in
        p) $cmd -e "SHOW PROCESSLIST" ;;
        d) $cmd -e "SHOW DATABASES" ;;
        t) $cmd -e "SHOW TABLES" ;;
        f) $cmd < "$DT_FILE" ;;
        *) $cmd -e "$query"
    # SHOW FULL COLUMS FROM $query
    # SELECT * FROM $query
    esac

elif [ "$1" = 'rev' ]; then # git revision

    git show "HEAD$DT_HEAD_REF:./$DT_FILE"

elif [ "$1" = 'vim' ]; then # link .vimrc

    ln -s "$DIR/.vimrc" "$HOME/.vimrc"

elif [ "$1" = 'upd' ]; then # update repo

    cd "$DIR"
    git pull --ff-only

fi
