#!/bin/bash

# env vars:
#
# DTF - file argument
# DTC - command argument
# DTQ - query argument
# DTL - MySQL login path (incl. database)
# DTM - modifier for git HEAD


DIR="${BASH_SOURCE%/*}"
if [ ! -d "$DIR" ]; then
    DIR="$PWD";
fi

if [ -n "$2" ]; then
    DTF="$2"
    DTC="$2"
    DTQ="$2"
fi

if [ "$1" = 'run' ]; then # execute command

    echo "$PWD $DTC"
    date
    echo "==="
    eval $DTC
    echo "==="
    date
    echo "$PWD $DTC"

elif [ "$1" = 'pyt' ]; then # python REPL

    python3

elif [ "$1" = 'pyl' ]; then # pylint

    pylint --output-format=parseable -sn "$DTF" | grep -v '\*\*'

elif [ "$1" = 'ggl' ]; then # google search

    query="${DTQ// /%20}"
    lynx -accept_all_cookies "google.com/search?q=$query"

elif [ "$1" = 'git' ]; then # git shell

    bash --rcfile "$DIR/git-env/.bashrc"
    # zsh version:
    # ZDOTDIR="$DIR/git-env" zsh

elif [ "$1" = 'sql' ]; then # query database

    cmd="mysql --login-path=$DTL -vv"
    case $DTQ in
        p)  query="SHOW PROCESSLIST" ;;
        d)  query="SHOW DATABASES" ;;
        t)  query="SHOW TABLES" ;;
        *)  query="${DTQ//\"/\\\"}"
            query="${query//\?/DESCRIBE}"
            query="${query//\#/SELECT COUNT(*) FROM}"
            query="${query//\!/SELECT * FROM}" ;;
    esac
    $cmd -e "$query"

elif [ "$1" = 'rev' ]; then # git revision

    git show "HEAD$DTM:./$DTF"

elif [ "$1" = 'vim' ]; then # link .vimrc

    ln -s "$DIR/.vimrc" "$HOME/.vimrc"

elif [ "$1" = 'upd' ]; then # update dotfiles

    cd "$DIR"
    git pull --ff-only

fi
