#!/bin/bash

cd "${BASH_SOURCE%/*}"
DOT_DIR=`pwd`

if [[ $OSTYPE == darwin* ]]; then
  RC="$HOME/.zshrc"
else
  RC="$HOME/.bashrc"
fi

echo "alias v='vim -u $DOT_DIR/vimrc'" >> $RC
echo "alias g='git -c \"include.path=$DOT_DIR/gitconfig\"'" >> $RC
echo "alias l='ls -lhp'" >> $RC
echo "alias la='ls -lhpA'" >> $RC

echo "updated $RC"

